line-length = 100
target-version = "py312"

[lint]
select = ["ALL"]
ignore = [
    "COM812",
    "CPY001",
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D106",
    "D107",
    "D203",
    "D212",
    "INP001",
    "S101",
]

[lint.per-file-ignores]
"packages/ravage/tests/fixtures/repository_review_eval/**/*.py" = ["S602", "S603"]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
