"""Side-effect-free setup diagnostics for the operator CLI."""

from __future__ import annotations

import json
import os
import shlex
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Literal
from urllib.parse import urlsplit, urlunsplit

import yaml  # type: ignore[import-untyped]

from ravage.cli_run_display import redacted_target_url
from ravage.labs import DEFAULT_LABS_DIR, list_labs
from ravage.tool_paths import is_executable_file
from ravage.web_core.http_probe import ProbeSession
from ravage.web_core.scope_policy import is_local_url

if TYPE_CHECKING:
    from collections.abc import Sequence

type DiagnosticStatus = Literal["ok", "warn", "fail"]

_DETAIL_CHARS = 300
_DOCKER_CHECK_TIMEOUT_SECONDS = 10
_MODEL_CHECK_TIMEOUT_SECONDS = 3
_HTTP_OK_MIN = 200
_HTTP_OK_MAX = 300
_HTTP_SERVER_ERROR_MIN = 500


@dataclass(frozen=True)
class SetupDiagnostic:
    """One human- and machine-readable readiness result."""

    name: str
    status: DiagnosticStatus
    detail: str
    fix: str = ""

    def to_dict(self) -> dict[str, str]:
        payload = {
            "name": self.name,
            "status": self.status,
            "detail": self.detail,
        }
        if self.fix:
            payload["fix"] = self.fix
        return payload


def discover_brief(*, directory: Path | None = None) -> Path | None:
    """Find an unambiguous conventional brief in ``directory``."""
    root = Path.cwd() if directory is None else directory
    for name in ("ravage-brief.yaml", "ravage-brief.yml", "brief.yaml", "brief.yml"):
        candidate = root / name
        if candidate.is_file():
            return candidate
    return None


def discover_env_file(*, brief_path: Path | None = None) -> Path | None:
    """Find the private environment file generated by ``ravage init``."""
    directory = brief_path.parent if brief_path is not None else Path.cwd()
    for name in (".env.ravage", ".env"):
        candidate = directory / name
        if candidate.is_file():
            return candidate
    return None


def run_location_diagnostic(path: Path = Path("runs")) -> SetupDiagnostic:
    candidate = path.resolve(strict=False)
    if candidate.exists() and not candidate.is_dir():
        return SetupDiagnostic(
            name="run_location",
            status="fail",
            detail=f"{path} exists but is not a directory",
            fix="Choose a writable directory with --run-root.",
        )
    parent = candidate if candidate.exists() else _nearest_existing_parent(candidate)
    if parent is None or not os.access(parent, os.W_OK):
        return SetupDiagnostic(
            name="run_location",
            status="fail",
            detail=f"cannot write run artifacts under {path}",
            fix="Choose a writable working directory or pass --run-root.",
        )
    return SetupDiagnostic(
        name="run_location",
        status="ok",
        detail=f"run artifacts can be written under {path}",
    )


def playwright_diagnostic(*, required: bool) -> SetupDiagnostic:
    status: DiagnosticStatus = "fail" if required else "warn"
    try:
        executable = _playwright_executable()
    except ModuleNotFoundError as exc:
        return SetupDiagnostic(
            name="browser",
            status=status,
            detail=f"Playwright is not installed ({_concise(exc)})",
            fix=_browser_setup_command(include_package=True),
        )
    except Exception as exc:  # noqa: BLE001 - optional dependency probe.
        return SetupDiagnostic(
            name="browser",
            status=status,
            detail=f"Playwright could not inspect Chromium ({_concise(exc)})",
            fix=_browser_setup_command(include_package=False),
        )
    if not executable.is_file():
        return SetupDiagnostic(
            name="browser",
            status=status,
            detail="Playwright is installed, but its Chromium browser is missing",
            fix=_browser_setup_command(include_package=False),
        )
    if not is_executable_file(executable):
        return SetupDiagnostic(
            name="browser",
            status=status,
            detail=f"Playwright Chromium is not executable: {executable}",
            fix=_browser_setup_command(include_package=False),
        )
    return SetupDiagnostic(
        name="browser",
        status="ok",
        detail=f"Playwright Chromium is ready at {executable}",
    )


def docker_compose_diagnostic(*, required: bool) -> SetupDiagnostic:
    missing_status: DiagnosticStatus = "fail" if required else "warn"
    docker = shutil.which("docker")
    if not docker:
        return SetupDiagnostic(
            name="docker",
            status=missing_status,
            detail="Docker was not found; core localhost scans still work without it",
            fix="Install and start Docker Desktop or Docker Engine.",
        )
    try:
        daemon = subprocess.run(  # noqa: S603
            [docker, "info", "--format", "{{.ServerVersion}}"],
            capture_output=True,
            text=True,
            timeout=_DOCKER_CHECK_TIMEOUT_SECONDS,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        return SetupDiagnostic(
            name="docker",
            status=missing_status,
            detail=f"Docker could not be checked ({_concise(exc)})",
            fix="Start Docker, then rerun `ravage doctor`.",
        )
    if daemon.returncode != 0:
        detail = _concise_text(daemon.stderr or daemon.stdout or "Docker daemon unavailable")
        return SetupDiagnostic(
            name="docker",
            status=missing_status,
            detail=f"Docker daemon is not ready ({detail})",
            fix="Start Docker Desktop or the Docker daemon, then rerun this check.",
        )
    try:
        compose = subprocess.run(  # noqa: S603
            [docker, "compose", "version", "--short"],
            capture_output=True,
            text=True,
            timeout=_DOCKER_CHECK_TIMEOUT_SECONDS,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        return SetupDiagnostic(
            name="docker",
            status=missing_status,
            detail=f"Docker is ready, but Compose could not be checked ({_concise(exc)})",
            fix="Install the Docker Compose plugin, then rerun this check.",
        )
    if compose.returncode != 0:
        return SetupDiagnostic(
            name="docker",
            status=missing_status,
            detail="Docker is ready, but the Compose plugin is unavailable",
            fix="Install the Docker Compose plugin, then rerun this check.",
        )
    version = compose.stdout.strip() or "available"
    return SetupDiagnostic(
        name="docker",
        status="ok",
        detail=f"Docker {daemon.stdout.strip() or 'daemon ready'}; Compose {version}",
    )


def labs_diagnostic(
    *,
    required: bool,
    labs_dir: Path = DEFAULT_LABS_DIR,
) -> SetupDiagnostic:
    try:
        manifests = list_labs(labs_dir=labs_dir)
    except (OSError, TypeError, ValueError, yaml.YAMLError) as exc:
        return SetupDiagnostic(
            name="labs",
            status="fail" if required else "warn",
            detail=f"lab definitions could not be loaded ({_concise(exc)})",
            fix=(
                f"Correct the manifests in {labs_dir}, or set RAVAGE_LABS_DIR to a valid "
                "examples/labs directory."
            ),
        )
    if manifests:
        return SetupDiagnostic(
            name="labs",
            status="ok",
            detail=f"{len(manifests)} included lab(s) found in {labs_dir}",
        )
    return SetupDiagnostic(
        name="labs",
        status="fail" if required else "warn",
        detail=f"no included labs found in {labs_dir}",
        fix=(
            "Run from a Ravage source checkout or set RAVAGE_LABS_DIR to its "
            "examples/labs directory."
        ),
    )


def target_reachability_diagnostic(  # noqa: PLR0913
    target_url: str,
    *,
    in_scope: Sequence[str],
    out_of_scope: Sequence[str],
    max_rps: int | None,
    allow_remote_target: bool,
    required: bool,
    timeout_seconds: int = 5,
) -> SetupDiagnostic:
    if not is_local_url(target_url) and not allow_remote_target:
        return SetupDiagnostic(
            name="target",
            status="fail" if required else "warn",
            detail="remote target was not contacted without explicit authorization",
            fix="Review scope, then rerun with --authorized-remote-target.",
        )
    try:
        session = ProbeSession(
            target_url,
            timeout_seconds=timeout_seconds,
            allow_remote_target=allow_remote_target,
            in_scope=in_scope,
            out_of_scope=out_of_scope,
            max_rps=max_rps,
        )
        response = session.get(target_url)
    except (OSError, ValueError) as exc:
        return SetupDiagnostic(
            name="target",
            status="fail" if required else "warn",
            detail=f"target readiness check failed ({_concise(exc)})",
            fix=_target_fix(target_url),
        )
    if response.status is None:
        return SetupDiagnostic(
            name="target",
            status="fail" if required else "warn",
            detail=f"no HTTP response from target ({_concise_text(response.error)})",
            fix=_target_fix(target_url),
        )
    if response.status >= _HTTP_SERVER_ERROR_MIN:
        return SetupDiagnostic(
            name="target",
            status="fail" if required else "warn",
            detail=(
                f"target is reachable but not ready (HTTP {response.status} from "
                f"{redacted_target_url(response.final_url or target_url)})"
            ),
            fix=_target_fix(target_url),
        )
    return SetupDiagnostic(
        name="target",
        status="ok",
        detail=(
            f"HTTP {response.status} from "
            f"{redacted_target_url(response.final_url or target_url)}"
        ),
    )


def local_model_diagnostic(  # noqa: PLR0911, PLR0913
    *,
    provider: str,
    model: str,
    base_url: str,
    api_key: str = "",
    required: bool = True,
    timeout_seconds: int = _MODEL_CHECK_TIMEOUT_SECONDS,
) -> SetupDiagnostic:
    """Verify a local OpenAI-compatible model route without generating content."""
    status: DiagnosticStatus = "fail" if required else "warn"
    try:
        endpoint = _model_listing_url(base_url)
    except ValueError as exc:
        return SetupDiagnostic(
            name="model",
            status=status,
            detail=f"invalid local model endpoint ({_concise(exc)})",
            fix="Correct the local model base URL, then rerun `ravage doctor`.",
        )

    headers = {"Accept": "application/json"}
    if api_key:
        headers["Authorization"] = f"Bearer {api_key}"
    try:
        session = ProbeSession(
            endpoint,
            timeout_seconds=max(1, min(timeout_seconds, 10)),
            default_headers=headers,
            allow_remote_target=False,
            in_scope=(endpoint,),
            out_of_scope=(),
            max_rps=None,
        )
        response = session.get(endpoint)
    except (OSError, TypeError, ValueError) as exc:
        return SetupDiagnostic(
            name="model",
            status=status,
            detail=f"local model endpoint is unavailable ({_concise(exc)})",
            fix=_local_model_fix(provider, model),
        )
    if response.status is None:
        return SetupDiagnostic(
            name="model",
            status=status,
            detail=f"local model endpoint is unavailable ({_concise_text(response.error)})",
            fix=_local_model_fix(provider, model),
        )
    if not _HTTP_OK_MIN <= response.status < _HTTP_OK_MAX:
        return SetupDiagnostic(
            name="model",
            status=status,
            detail=f"local model endpoint returned HTTP {response.status}",
            fix=_local_model_fix(provider, model),
        )
    if response.truncated:
        return SetupDiagnostic(
            name="model",
            status=status,
            detail="local model listing exceeded the diagnostic response limit",
            fix=_local_model_fix(provider, model),
        )
    try:
        payload = json.loads(response.body)
    except (json.JSONDecodeError, TypeError) as exc:
        return SetupDiagnostic(
            name="model",
            status=status,
            detail=f"local model endpoint returned invalid JSON ({_concise(exc)})",
            fix=_local_model_fix(provider, model),
        )
    available = _listed_model_ids(payload)
    if model not in available:
        return SetupDiagnostic(
            name="model",
            status=status,
            detail=f"{provider}/{model} is not available from the local model endpoint",
            fix=_local_model_fix(provider, model),
        )
    return SetupDiagnostic(
        name="model",
        status="ok",
        detail=f"{provider}/{model} is available locally",
    )


def _nearest_existing_parent(path: Path) -> Path | None:
    current = path
    while not current.exists() and current != current.parent:
        current = current.parent
    return current if current.exists() else None


def _model_listing_url(base_url: str) -> str:
    if not is_local_url(base_url):
        message = "local model diagnostics only contact loopback URLs"
        raise ValueError(message)
    try:
        parsed = urlsplit(base_url)
        _ = parsed.port
    except ValueError as exc:
        message = "local model base URL is invalid"
        raise ValueError(message) from exc
    path = parsed.path.rstrip("/")
    if not path.endswith("/models"):
        path += "/models"
    return urlunsplit((parsed.scheme, parsed.netloc, path, "", ""))


def _listed_model_ids(payload: object) -> set[str]:
    if not isinstance(payload, dict):
        return set()
    items = payload.get("data")
    if not isinstance(items, list):
        items = payload.get("models")
    if not isinstance(items, list):
        return set()
    result: set[str] = set()
    for item in items:
        if not isinstance(item, dict):
            continue
        for key in ("id", "name", "model"):
            value = item.get(key)
            if isinstance(value, str) and value.strip():
                result.add(value.strip())
                break
    return result


def _local_model_fix(provider: str, model: str) -> str:
    return (
        f"Start {provider}, install or load {model}, then rerun `ravage doctor`."
    )


def _playwright_executable() -> Path:
    from playwright.sync_api import (  # type: ignore[import-not-found]  # noqa: PLC0415
        sync_playwright,
    )

    with sync_playwright() as playwright:
        return Path(playwright.chromium.executable_path)


def _browser_setup_command(*, include_package: bool) -> str:
    checkout_script = Path(__file__).resolve().parents[4] / "scripts" / "bootstrap.sh"
    if checkout_script.is_file():
        return "Run `scripts/bootstrap.sh --install-browser`."
    if include_package:
        return (
            "Install the browser extra, then Chromium: `python -m pip install "
            "'ravage[browser]' && python -m playwright install chromium`."
        )
    return "Run `python -m playwright install chromium`."


def _target_fix(target_url: str) -> str:
    if is_local_url(target_url):
        safe_target = shlex.quote(redacted_target_url(target_url))
        return f"Start the application and verify its URL: `curl -I {safe_target}`."
    return "Check target DNS/TLS and the authorized scope, then retry."


def _concise(exc: BaseException) -> str:
    return _concise_text(str(exc) or type(exc).__name__)


def _concise_text(value: str) -> str:
    first = value.strip().splitlines()[:1]
    return (first[0] if first else "unknown error")[:_DETAIL_CHARS]


__all__ = [
    "SetupDiagnostic",
    "discover_brief",
    "discover_env_file",
    "docker_compose_diagnostic",
    "labs_diagnostic",
    "local_model_diagnostic",
    "playwright_diagnostic",
    "run_location_diagnostic",
    "target_reachability_diagnostic",
]
