from pathlib import Path

from scripts.qa.check_docs import _missing_repo_paths


def test_missing_repo_paths_accepts_existing_root_relative_path(tmp_path: Path) -> None:
    referenced = tmp_path / "packages" / "example" / "test_example.py"
    referenced.parent.mkdir(parents=True)
    referenced.write_text("", encoding="utf-8")
    document = tmp_path / "docs" / "guide.md"

    errors = _missing_repo_paths(
        document,
        "Run `packages/example/test_example.py`.\n",
        root=tmp_path,
    )

    assert errors == []


def test_missing_repo_paths_reports_stale_command_path(tmp_path: Path) -> None:
    document = tmp_path / "docs" / "guide.md"

    errors = _missing_repo_paths(
        document,
        "Run `packages/example/tests/test_removed.py`.\n",
        root=tmp_path,
    )

    assert errors == [
        "docs/guide.md:1: missing repository path: packages/example/tests/test_removed.py"
    ]


def test_missing_repo_paths_ignores_runtime_and_glob_paths(tmp_path: Path) -> None:
    document = tmp_path / "docs" / "guide.md"
    text = (
        "Read `RUN_DIR/report.json` and run "
        "`packages/example/tests/test_generated_*.py`.\n"
    )

    assert _missing_repo_paths(document, text, root=tmp_path) == []


def test_missing_repo_paths_does_not_validate_an_extension_prefix(tmp_path: Path) -> None:
    document = tmp_path / "docs" / "guide.md"

    # ``.pyc`` is outside the maintained-source matcher. It must not be
    # truncated to a nonexistent ``.py`` path and reported as a stale link.
    assert _missing_repo_paths(
        document,
        "Generated bytecode: `packages/example/module.pyc`.\n",
        root=tmp_path,
    ) == []


def test_missing_repo_paths_rejects_path_that_leaves_repository(tmp_path: Path) -> None:
    document = tmp_path / "docs" / "guide.md"

    errors = _missing_repo_paths(
        document,
        "Do not use `docs/../../outside.md`.\n",
        root=tmp_path,
    )

    assert errors == [
        "docs/guide.md:1: repository path leaves root: docs/../../outside.md"
    ]
