from pathlib import Path

from scripts.qa.check_docs import (
    _missing_repo_paths,
    _missing_required_docs,
    _public_install_errors,
)


def test_missing_repo_paths_accepts_existing_root_relative_path(tmp_path: Path) -> None:
    referenced = tmp_path / "packages" / "example" / "test_example.py"
    referenced.parent.mkdir(parents=True)
    referenced.write_text("", encoding="utf-8")
    document = tmp_path / "docs" / "guide.md"

    errors = _missing_repo_paths(
        document,
        "Run `packages/example/test_example.py`.\n",
        root=tmp_path,
    )

    assert errors == []


def test_missing_repo_paths_reports_stale_command_path(tmp_path: Path) -> None:
    document = tmp_path / "docs" / "guide.md"

    errors = _missing_repo_paths(
        document,
        "Run `packages/example/tests/test_removed.py`.\n",
        root=tmp_path,
    )

    assert errors == [
        "docs/guide.md:1: missing repository path: packages/example/tests/test_removed.py"
    ]


def test_missing_repo_paths_ignores_runtime_and_glob_paths(tmp_path: Path) -> None:
    document = tmp_path / "docs" / "guide.md"
    text = (
        "Read `RUN_DIR/report.json` and run "
        "`packages/example/tests/test_generated_*.py`.\n"
    )

    assert _missing_repo_paths(document, text, root=tmp_path) == []


def test_missing_repo_paths_does_not_validate_an_extension_prefix(tmp_path: Path) -> None:
    document = tmp_path / "docs" / "guide.md"

    # ``.pyc`` is outside the maintained-source matcher. It must not be
    # truncated to a nonexistent ``.py`` path and reported as a stale link.
    assert _missing_repo_paths(
        document,
        "Generated bytecode: `packages/example/module.pyc`.\n",
        root=tmp_path,
    ) == []


def test_missing_repo_paths_rejects_path_that_leaves_repository(tmp_path: Path) -> None:
    document = tmp_path / "docs" / "guide.md"

    errors = _missing_repo_paths(
        document,
        "Do not use `docs/../../outside.md`.\n",
        root=tmp_path,
    )

    assert errors == [
        "docs/guide.md:1: repository path leaves root: docs/../../outside.md"
    ]


def test_missing_required_docs_reports_absent_file(tmp_path: Path) -> None:
    required = tmp_path / "RELEASING.md"

    assert _missing_required_docs((required,), root=tmp_path) == [
        "missing required document: RELEASING.md"
    ]


def test_public_install_requires_exact_current_version(tmp_path: Path) -> None:
    document = tmp_path / "README.md"
    text = 'python -m pip install "ravage==0.5.0" # x-release-please-version\n'

    assert _public_install_errors(document, text, "0.6.0", root=tmp_path) == [
        "README.md:1: public install spec 'ravage==0.5.0' must use exact version 0.6.0"
    ]


def test_public_install_accepts_base_and_browser_pins(tmp_path: Path) -> None:
    document = tmp_path / "README.md"
    text = (
        'python -m pip install "ravage==0.6.0" # x-release-please-version\n'
        'python -m pip install "ravage[browser]==0.6.0" # x-release-please-version\n'
    )

    assert _public_install_errors(document, text, "0.6.0", root=tmp_path) == []


def test_public_install_ignores_editable_source_path(tmp_path: Path) -> None:
    document = tmp_path / "README.md"
    text = "python -m pip install -e packages/ravage\n"

    assert _public_install_errors(document, text, "0.6.0", root=tmp_path) == [
        "README.md: missing version-pinned public install command"
    ]


def test_public_install_requires_release_please_marker(tmp_path: Path) -> None:
    document = tmp_path / "README.md"
    text = 'python -m pip install "ravage==0.6.0"\n'

    assert _public_install_errors(document, text, "0.6.0", root=tmp_path) == [
        "README.md:1: public install pin is missing the Release Please version marker"
    ]
