"""Identity-isolated authentication sessions and secret-safe lifecycle hooks."""

from .configured import (
    ConfiguredAuthenticationError,
    UnsupportedConfiguredAuthFlowError,
    assert_secure_configured_auth_transport,
    identity_profile_from_config,
    identity_profiles_from_config,
)
from .preflight import (
    AuthPreflightResult,
    AuthPreflightStage,
    AuthPreflightStageName,
    AuthPreflightStageStatus,
    run_auth_preflight,
)
from .redaction import AuthArtifactRedactor, is_contextual_identity_secret_name
from .runtime import ManagedAttackAuthentication, build_authenticated_attack_runtime
from .scaffold import (
    AuthScaffoldError,
    AuthScaffoldResult,
    ScaffoldAuthMethod,
    default_secret_environment_key,
    resolve_auth_url,
    scaffold_auth_identity,
)
from .secrets import (
    EnvironmentFileError,
    EnvironmentSecretResolver,
    MappingSecretResolver,
    SecretRef,
    SecretResolutionError,
    SecretResolver,
    SecretSnapshotResolver,
    SecretValue,
    environment_secret_resolver,
    read_environment_file,
)
from .sessions import (
    AuthenticationError,
    HealthCheckCallback,
    HealthCheckError,
    IdentityProfile,
    IdentitySecrets,
    LoginCallback,
    SessionError,
    SessionHandle,
    SessionHealth,
    SessionLifecycle,
    SessionManager,
    SessionManagerClosedError,
    SessionRequestPolicy,
    SessionSnapshot,
    UnknownIdentityError,
)

__all__ = [
    "AuthArtifactRedactor",
    "AuthPreflightResult",
    "AuthPreflightStage",
    "AuthPreflightStageName",
    "AuthPreflightStageStatus",
    "AuthScaffoldError",
    "AuthScaffoldResult",
    "AuthenticationError",
    "ConfiguredAuthenticationError",
    "EnvironmentFileError",
    "EnvironmentSecretResolver",
    "HealthCheckCallback",
    "HealthCheckError",
    "IdentityProfile",
    "IdentitySecrets",
    "LoginCallback",
    "MappingSecretResolver",
    "ManagedAttackAuthentication",
    "ScaffoldAuthMethod",
    "SecretRef",
    "SecretResolutionError",
    "SecretResolver",
    "SecretSnapshotResolver",
    "SecretValue",
    "SessionError",
    "SessionHandle",
    "SessionHealth",
    "SessionLifecycle",
    "SessionManager",
    "SessionManagerClosedError",
    "SessionRequestPolicy",
    "SessionSnapshot",
    "UnknownIdentityError",
    "UnsupportedConfiguredAuthFlowError",
    "assert_secure_configured_auth_transport",
    "build_authenticated_attack_runtime",
    "default_secret_environment_key",
    "environment_secret_resolver",
    "identity_profile_from_config",
    "identity_profiles_from_config",
    "is_contextual_identity_secret_name",
    "read_environment_file",
    "resolve_auth_url",
    "run_auth_preflight",
    "scaffold_auth_identity",
]
