from __future__ import annotations

import re

SQL_CONFIRMATION_MARKERS = (
    "sql_injection_error_signal",
    "blind_sql_injection_boolean_signal",
    "blind_sql_injection_timing_signal",
    "sql_error_leak_primitive",
    "sql_union_primitive",
    "sql_boolean_primitive",
)

ERROR_SIGNAL_MARKERS = ("traceback", "exception", "sql syntax", "sqlite")
SURFACE_SIGNAL_MARKERS = ("<form", "set-cookie", "href=", "action=")
DATABASE_FACT_MARKERS = ("sql syntax", "sqlite", "mysql", "postgres")
SQL_FACT_MARKERS = ("sql_injection_error_signal", "blind_sql_injection", "sql_error_leak_primitive")
SERVER_ERROR_FACT_MARKERS = ("traceback", "exception", "stack trace")

SQL_RELEVANT_FINDING_TYPES = frozenset(
    {
        "data_query_signal",
        "filtered_query_bypass_signal",
        "filtered_query_exposed_secret",
        "filtered_query_sql_error_signal",
        "preg_match_subject_type_signal",
        "preg_match_subject_match",
        "preg_match_subject_synthetic_match",
        "preg_match_subject_proof",
        "sql_extracted_proof",
    }
)

FILE_READ_FINDING_TYPES = {
    "file_read_primitive",
    "file_fetch_parser_signal",
    "file_read_extracted_content",
    "file_read_extracted_proof",
    "file_read_listed_file_proof",
    "file_read_listed_file_secret",
    "php_include_execution",
    "php_include_extracted_proof",
}

APACHE_TRAVERSAL_PATTERN = re.compile(r"apache/2\.4\.(?:49|50)\b", flags=re.IGNORECASE)

CONFIRMATION_FINDING_TYPES = frozenset(
    {
        "client_side_execution",
        "client_side_proof_extraction",
        "reflection_value_delta",
        "reflection_value_timeout",
        "reflection_value_proof",
        "ssrf_boundary_signal",
        "ssrf_internal_path_signal",
        "ssrf_extracted_secret",
        "ssrf_extracted_proof",
        "two_identity_session_delta",
        "sql_injection_error_signal",
        "sql_error_leak_primitive",
        "sql_union_primitive",
        "sql_boolean_primitive",
        "blind_sql_injection_boolean_signal",
        "blind_sql_injection_timing_signal",
        "sqli_auth_bypass_session",
        "data_query_signal",
        "sql_literal_comment_exposed_secret",
        "sql_literal_comment_bypass_signal",
        "filtered_query_bypass_signal",
        "filtered_query_exposed_secret",
        "filtered_query_sql_error_signal",
        "preg_match_subject_type_signal",
        "preg_match_subject_match",
        "preg_match_subject_synthetic_match",
        "preg_match_subject_proof",
        "sql_extracted_proof",
        "command_boundary_proof",
        "command_boundary_signal",
        "command_boundary_timing_signal",
        "command_blind_extraction",
        "ssti_fingerprint_signal",
        "ssti_engine_execution",
        "ssti_extracted_proof",
        "ssti_stored_signal",
        "file_read_primitive",
        "file_fetch_parser_signal",
        "file_read_extracted_content",
        "file_read_extracted_proof",
        "file_read_listed_file_proof",
        "file_read_listed_file_secret",
        "php_include_execution",
        "php_include_extracted_proof",
        "apache_2_4_path_traversal_surface",
        "xxe_file_read_signal",
        "xxe_extracted_proof",
        "file_upload_deserialization_side_effect_proof",
        "direct_exposure_proof",
        "direct_exposure_candidate",
        "direct_exposure_listed_file_proof",
        "direct_exposure_listed_file_secret",
        "idor_boundary_signal",
        "idor_boundary_followup_signal",
        "idor_boundary_followup_exposed_secret",
        "idor_boundary_exposed_secret",
        "idor_cookie_identity_signal",
        "idor_cookie_identity_exposed_secret",
        "idor_identity_header_exposed_secret",
        "vertical_idor_privilege_field",
        "jwt_observed",
        "graphql_schema_signal",
        "graphql_exposed_proof",
        "file_upload_sink_reachable",
        "file_upload_extracted_proof",
        "file_upload_saved_path",
        "insecure_deserialization_cookie_signal",
        "cookie_deserialization_marker",
        "cookie_deserialization_extracted_proof",
        "jwt_secret_cracked",
        "jwt_forgery_signal",
        "jwt_extracted_proof",
        "graphql_schema_mapped",
        "graphql_mutation_discovered",
        "graphql_extracted_proof",
        "graphql_argument_injection_signal",
        "cms_backup_artifact",
        "cms_plugin_version_signal",
        "cms_exposure_extracted_proof",
        "privilege_escalation_signal",
        "cookie_privilege_tamper_signal",
        "default_credentials_valid",
        "auth_workflow_progress_signal",
        "auth_workflow_completed_signal",
        "auth_extracted_proof",
        "session_followup_proof",
        "deferred_form_flow_signal",
        "csrf_omission_accepted",
        "csrf_omission_extracted_proof",
        "csrf_token_reuse_signal",
        "csrf_token_reuse_extracted_proof",
        "csrf_session_extracted_proof",
        "logout_invalidation_failed",
        "session_cookie_attribute_signal",
        "cors_misconfiguration_signal",
        "cors_extracted_proof",
        "clickjacking_frame_policy_missing",
        "websocket_cross_origin_handshake_signal",
        "browser_storage_secret_exposure",
        "werkzeug_console_exposed",
        "werkzeug_console_unlocked",
        "werkzeug_console_extracted_proof",
        "captcha_form_state_proof",
    }
)
