from __future__ import annotations

SKILL_PROBE_MAP: dict[str, tuple[str, ...]] = {
    "analyze-satcom": (),
    "hunt-api-misconfig": ("api_behavior", "browser_boundary", "jwt_exploit"),
    "hunt-auth-bypass": ("stateful_session", "default_credentials", "sqli_exploit"),
    "hunt-brute-force": ("stateful_session",),
    "hunt-business-logic": ("stateful_session", "idor_boundary"),
    "hunt-cache-poison": ("browser_boundary",),
    "hunt-cors": ("browser_boundary",),
    "hunt-csrf": ("csrf_session",),
    "hunt-deserialization": ("cookie_deserialization", "file_fetch_parser"),
    "hunt-dom": ("xss_context", "dom_execution", "browser_boundary"),
    "hunt-file-upload": ("file_fetch_parser", "xxe_boundary"),
    "hunt-graphql": ("api_behavior", "graphql_exploit", "idor_boundary"),
    "hunt-host-header": ("browser_boundary", "ssrf_boundary"),
    "hunt-http-smuggling": ("browser_boundary",),
    "hunt-idor": ("idor_boundary", "api_behavior", "graphql_exploit"),
    "hunt-lfi": ("file_fetch_parser", "file_read_extract"),
    "hunt-mfa-bypass": ("stateful_session",),
    "hunt-nextjs": ("direct_exposure", "ssrf_boundary", "file_fetch_parser"),
    "hunt-nodejs": ("command_boundary", "file_fetch_parser", "ssti_fingerprint"),
    "hunt-nosqli": ("data_query",),
    "hunt-oauth": ("stateful_session", "browser_boundary"),
    "hunt-open-redirect": ("ssrf_boundary", "browser_boundary"),
    "hunt-race-condition": ("stateful_session",),
    "hunt-rce": (
        "command_boundary",
        "werkzeug_console",
        "ssti_fingerprint",
        "file_fetch_parser",
    ),
    "hunt-saml": ("stateful_session",),
    "hunt-session": ("stateful_session", "csrf_session", "jwt_exploit"),
    "hunt-source-leak": ("direct_exposure", "secret_sweep"),
    "hunt-sqli": ("sqli_differential", "sqli_exploit", "filtered_query_bypass"),
    "hunt-ssrf": ("ssrf_boundary", "file_fetch_parser"),
    "hunt-ssti": ("ssti_fingerprint", "command_boundary"),
    "hunt-websocket": ("browser_boundary",),
    "hunt-xss": ("xss_context", "dom_execution", "reflection_value_boundary"),
    "hunt-xxe": ("xxe_boundary", "file_fetch_parser"),
}

SKILL_KEYWORDS: dict[str, tuple[str, ...]] = {
    "analyze-satcom": (
        "satcom",
        "satellite",
        "spacecraft",
        "ccsds",
        "satellite telemetry",
        "space telemetry packet",
        "telecommand",
        "two-line element",
        "tle",
        "afsk",
        "iq samples",
    ),
    "hunt-api-misconfig": ("api", "json", "mass assignment", "verb tampering", "jwt"),
    "hunt-auth-bypass": ("auth bypass", "login bypass", "authentication", "password"),
    "hunt-brute-force": ("brute force", "rate limit", "otp", "captcha"),
    "hunt-business-logic": ("business logic", "workflow", "price", "coupon", "transfer"),
    "hunt-cache-poison": ("cache", "poison", "unkeyed"),
    "hunt-cors": ("cors", "access-control-allow-origin", "origin"),
    "hunt-csrf": ("csrf", "xsrf", "state-changing", "samesite"),
    "hunt-deserialization": (
        "deserialize",
        "deserialization",
        "serialized cookie",
        "pickle",
        "pickle file",
        "php serialize",
        "java object stream",
        "objectinputstream",
        "yaml object tag",
    ),
    "hunt-dom": ("dom", "postmessage", "innerhtml", "localstorage"),
    "hunt-file-upload": (
        "file upload",
        "upload form",
        "multipart upload",
    ),
    "hunt-graphql": (
        "graphql",
        "graphiql",
        "graphql introspection",
        "introspection query",
        "__schema",
        "graphql mutation",
    ),
    "hunt-host-header": ("host header", "x-forwarded-host", "password reset"),
    "hunt-http-smuggling": ("smuggling", "cl.te", "te.cl", "http/2"),
    "hunt-idor": (
        "idor",
        "object id",
        "object reference",
        "user_id",
        "account_id",
        "org_id",
        "cross-tenant",
        "tenant authorization",
        "authorization boundary",
    ),
    "hunt-lfi": (
        "lfi",
        "local file inclusion",
        "path traversal",
        "arbitrary file read",
        "../",
    ),
    "hunt-mfa-bypass": ("mfa", "2fa", "otp", "totp"),
    "hunt-nextjs": ("next.js", "_next", "server actions", "middleware"),
    "hunt-nodejs": ("node", "express", "prototype pollution", "child_process"),
    "hunt-nosqli": ("nosql", "mongodb", "$where", "$ne", "$regex"),
    "hunt-oauth": ("oauth", "redirect_uri", "authorization code", "openid"),
    "hunt-open-redirect": ("open redirect", "redirect_uri", "next=", "return="),
    "hunt-race-condition": ("race", "concurrency", "parallel", "double spend"),
    "hunt-rce": (
        "rce",
        "remote code execution",
        "command injection",
        "os command",
        "code execution",
        "shell injection",
    ),
    "hunt-saml": ("saml", "sso", "assertion", "xml signature"),
    "hunt-session": ("session", "cookie", "jwt", "logout", "fixation"),
    "hunt-source-leak": ("source map", ".git", ".env", "backup", "source leak"),
    "hunt-sqli": (
        "sqli",
        "sql injection",
        "query injection",
        "union select",
    ),
    "hunt-ssrf": (
        "ssrf",
        "server-side request forgery",
        "url fetch",
        "server-side fetch",
        "webhook",
        "link preview",
        "image proxy",
    ),
    "hunt-ssti": (
        "ssti",
        "server-side template injection",
        "template injection",
        "jinja injection",
        "twig",
        "freemarker",
    ),
    "hunt-websocket": ("websocket", "ws://", "wss://", "socket"),
    "hunt-xss": (
        "xss",
        "cross-site scripting",
        "html injection",
    ),
    "hunt-xxe": (
        "xxe",
        "xml external entity",
        "external entity",
        "xml doctype",
        "xml parser",
        "soap endpoint",
        "soap service",
        "wsdl",
    ),
}

SKILL_TYPED_IDENTIFIERS: dict[str, tuple[str, ...]] = {
    "analyze-satcom": ("satcom_artifact", "ccsds_packet_stream"),
    "hunt-deserialization": (
        "cookie_deserialization",
        "deserialization",
        "insecure_deserialization",
        "insecure_deserialization_cookie_signal",
        "serialized_cookie_confirmed",
        "serialized_state_boundary",
        "serialized_object_surface",
    ),
    "hunt-file-upload": (
        "file_upload",
        "file_upload_surface",
        "file_upload_sink_reachable",
        "file_upload_saved_path",
        "file_upload_extracted_proof",
        "file_upload_deserialization_side_effect_proof",
        "arbitrary_file_upload",
    ),
    "hunt-graphql": (
        "graphql_exploit",
        "graphql_schema_available",
        "graphql_schema_signal",
        "graphql_schema_mapped",
        "graphql_surface",
    ),
    "hunt-idor": (
        "idor_boundary",
        "idor_boundary_signal",
        "idor_confirmed",
        "object_authorization",
        "object_authorization_surface",
    ),
    "hunt-lfi": (
        "apache_2_4_path_traversal_surface",
        "apache_traversal_surface",
        "file_read_confirmed",
        "file_read_extract",
        "file_read_inputs",
        "file_read_replays",
        "local_file_inclusion",
        "path_traversal",
    ),
    "hunt-rce": (
        "command_blind_confirmed",
        "command_boundary",
        "command_exec_confirmed",
        "command_execution_surface",
        "command_injection",
        "werkzeug_console_exposed",
        "werkzeug_console_unlocked",
    ),
    "hunt-sqli": (
        "blind_sqli_confirmed",
        "blind_sql_injection_boolean_signal",
        "blind_sql_injection_timing_signal",
        "filtered_query_bypass",
        "sql_injection",
        "sql_injection_confirmed",
        "sql_injection_error_signal",
        "sqli_boolean_templates",
        "sqli_confirmed",
        "sqli_differential",
        "sqli_exploit",
        "sqli_inputs",
        "sqli_replays",
    ),
    "hunt-ssrf": (
        "server_side_request_forgery",
        "ssrf_boundary",
        "ssrf_confirmed",
        "ssrf_fetch_surface",
    ),
    "hunt-ssti": (
        "server_side_template_injection",
        "ssti_confirmed",
        "ssti_fingerprint",
        "template_injection",
        "template_render_surface",
    ),
    "hunt-xss": (
        "client_side_execution",
        "client_xss_confirmed",
        "cross_site_scripting",
        "xss_context",
        "xss_contexts",
        "xss_filter_profile",
        "xss_reflection_context",
    ),
    "hunt-xxe": (
        "xml_external_entity",
        "xml_parser_surface",
        "xxe_boundary",
        "xxe_confirmed",
        "xxe_extracted_proof",
        "xxe_file_read_signal",
        "xxe_surface_observed",
    ),
}

ALL_SKILL_TYPED_IDENTIFIERS = frozenset(
    identifier for identifiers in SKILL_TYPED_IDENTIFIERS.values() for identifier in identifiers
)


def mapped_probes(skill_name: str) -> tuple[str, ...]:
    return SKILL_PROBE_MAP.get(skill_name, ())


def skill_keywords(skill_name: str) -> tuple[str, ...]:
    return SKILL_KEYWORDS.get(skill_name, ())


def skill_typed_identifiers(skill_name: str) -> tuple[str, ...]:
    return SKILL_TYPED_IDENTIFIERS.get(skill_name, ())
