name: Release Please

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    env:
      RELEASE_PLEASE_TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN != '' && secrets.RELEASE_PLEASE_TOKEN || secrets.GITHUB_TOKEN }}
          config-file: tools/release/release-please-config.json
          manifest-file: tools/release/.release-please-manifest.json
